---
- name: Installing Mysql and dependencies
  apt: name={{item}} state=present  update_cache=yes
  with_items:
      - mysql-server
      - python-mysqldb
  notify: mysql restart

- name: Starting Mysql service
  command: service mysql start warn=no
  ignore_errors: yes

- name: Mysql Secure Installation
  include: mysql_secure_installation.yml 
