---
- name: Downloading Mysql package
  get_url:
    url: https://dev.mysql.com/get/mysql-apt-config_0.8.13-1_all.deb
    dest: /tmp/mysql-apt-config_0.8.13-1_all.deb
    mode: '0644'

- name: Installing mysql package
  apt: "deb=/tmp/mysql-apt-config_0.8.13-1_all.deb"
  environment:
    DEBIAN_FRONTEND: noninteractive

- name: Installing mysql-server
  apt:
    name: mysql-server
    update_cache: yes
  notify: mysql_restart

- name: Mysql Secure Installation
  include: mysql_secure_installation.yml 
