---
- name: Checking pre-requisities on target Machine
  include_tasks: check-pre-requisities.yml

- name: Including tasks for RedHat Family
  include_tasks: redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Including tasks for Debian Family
  include_tasks: debian.yml
  when: ansible_os_family == 'Debian'
